Justfile
src/system/etc/lightdm/lightdm.conf
src/system/etc/sddm.conf.d/autologin.conf
src/system/etc/systemd/system/getty@tty1.service.d/autologin.conf
src/system/etc/systemd/system/multi-user.target.wants/livecd-user.service
src/system/usr/lib/systemd/system/livecd-user.service
src/system/usr/lib/tmpfiles.d/lightdm-autologin-override.conf
src/system/usr/libexec/create-livecd-user.sh

Creates a user called livecd with password livecd that is automatically logged in for SDDM. LightDM support is spotty.
This allows Aurora to boot directly to the desktop
```bash
$ just build ghcr.io/ublue-os/aurora:stable 1
```

 feat: create livecd user and autologin for SDDM/LightDM 

---

Justfile

This allows for quicker iteration if we dont want to re-setup the rootfs all the time

fix: only clean rootfs when needed

---

Justfile

This will be interpreted by `/bin/sh` which is not guaranteed to be Bash.

fix: add missing shebang for clean recipe

---

Justfile

dracut fails whenever `/root` is a symlink to `/var/roothome` and the later doesnt exists

fix(initramfs): create /root target in case is a symlink

---

Justfile

This is required in order to let bootc run at runtime without podman

chore(rootfs): Make /var/tmp a symlink pointing to /tmp

---

Justfile

This just removes the redundant argument. We dont even use the image on the squash recipe anymore so it should be fine :)

fix: remove $IMAGE argument from just squash

---

Justfile
src/fstab.sys

This entirely fixes the flatpak issues we were getting on the fat32 transition. Now we have fully functioning ISOs!

fix: readd flatpaks by squashing them into the ISO root

---

Justfile

This makes it so xdg-desktop-portal implementations work on the Live ISO environment

fix: let fusermount3 have setuid permissions

---

Justfile
action.yml

Implement reusable action with `hook-post-rootfs` input, allowing users to do customized changes to the rootfs without needing to apply them to the base image (such as placing their bootc installer of choice).
This solves #19

feat: add iso building action with rootfs hook

---

.github/workflows/ci.yml
Justfile
action.yml

Allows stuff like `bazzite-deck` to be distributed this way
Maybe the wording is a bit ambiguous, would love some suggestions here
Fixes: #42

feat: let target installer container image be different from ISO root

---

Justfile

We absolutely need this else podman will complain about the overlay storage driver not working

fix: readd fuse-overlayfs so that we can run `podman images` on installers

---

.github/workflows/ci.yml
Justfile
action.yml
src/polkit-1/rules.d/10-bootc-privileged.rules
src/polkit-1/rules.d/20-podman-privileged.rules

Will make our work a lot easier for installers! Just lets `pkexec bootc` and `pkexec podman` run without a password on the live environment
Fixes: #43

fix: add polkit rules for podman and bootc privileged without password 

---

Justfile

This typo was making aarch64 builds fail :P

fix: naming from aarch64 shim

---

.github/workflows/ci.yml
Justfile
action.yml

Honestly having this is much more consistent than having to account specifically for GNOME on some cases. livesys-scripts also make GNOME always launch directly into a live session instead of being annoying and sometimes launching you into that "Try and Install" thing, and sometimes launching you into a regular user creation

feat: use livesys scripts by default for all images

---

Justfile

I've been bitten a few times now by making changes to an image and not being able to see them in the live ISO because it is using an old image.

feat: podman pull if running locally

---

src/livesys-session-extra

We are overriding the `/var/lib/livesys/livesys-session-extra` script from the source image. This feature allows images to drop files in `/var/lib/livesys/livesys-session-extra.d` that will be run.
I will use this in Blue95 to change the default username from "Blue95 User" to something else.

feat: drop-in scripts for livesys-scripts

---

Justfile

Trying to pull a locally built image like `localhost/aurora:latest` fails. This guard skips the pull in this case.

fix: only pull non-localhost images

---

src/livesys-session-extra

fixes this here
KDE checks for `/etc/localtime` and seemingly doesn't care about anything else like `timedatectl` so this didn't work https://github.com/ublue-os/titanoboa/pull/60

fix: set /etc/localtime so KDE Plasma has a clock

---

Justfile

chore: use built-in arch() instead of `uname -m`
fix: don't cp squashfs in CI, move it

fix: allow non-app flatpaks to be listed in flatpak list

---

Justfile
src/grub.cfg.tmpl

'bluefin_boot' was an old placeholder name. Using a more generic name seems more adecuate, as now we use titanoboa across all our isos.

chore: use 'titanoboa_boot' as partition name

---

src/grub.cfg.tmpl

'Try OS_NAME' might give the wrong impression that the live ISO
environment fully mirrors a full install.

chore: Rename bootup entry in grub
